### ISSUE TITLE
weighted perturbation rank is eliminated

### ISSUE THREAD

**Issue by janwendt** [drcannady/pub#1]
Why is the weighted perturbation rank multiplied by 0?
Did you use it for testing purposes and forgot to remove it?
See:
https://github.com/drcannady/pub/blob/9df227e58e93892fd433ddd97d25e38eab3ac125/ijcnn-2017/stable_feature_ranking.py#L214

**Comment by jeffheaton** [comment]
That should not be there, I think that was something I added for debugging that slipped into the version I checked in.  I just removed it.
